name: DbCtl Core - Release

on:
  workflow_run:
    workflows: ["DbCtl Core - CI"]
    branches: [ main ]
    types:
      - completed

jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore src/DbCtl.Core.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore src/DbCtl.Core.sln
    - uses: nuget/setup-nuget@v1
      with:
        nuget-api-key: ${{ secrets.NUGETAPIKEY }}
        nuget-version: '5.x'
    - run: nuget pack -OutputFileNamesWithoutVersion ./src/DbCtl.Core.nuspec
    - run: nuget push ./DbCtl.Core.nupkg -source https://api.nuget.org/v3/index.json
